version: '3.7'
# To use Run `docker-compose -f docker-compose.development.yml up -d`

services:
  db:
    image: 'postgres'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
    networks:
      - pg-net
  
  pg4:
    depends_on:
      - db
    image: dpage/pgadmin4
    ports:
      - 8000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@domain.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
      - pg-net
  

networks:
  pg-net:

volumes:
  db_data:
