import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { useMemo, useRef, useState } from "react";

import "react-quill/dist/quill.snow.css";
import { CreateBlog } from "../services/blog/httpRequrest";
import axios from "axios";

const QuillNoSSRWrapper = dynamic(import("react-quill"), {
    ssr: false,
    loading: () => <p>Loading ...</p>,
});

// const EditorBlock = dynamic(() => import("../components/Editor"), {
//   ssr: false,
// });

export default function Home() {
    const modules = {
        toolbar: [
            [{ header: "1" }, { header: "2" }, { font: [] }],
            [{ size: [] }],
            ["bold", "italic", "underline", "strike", "blockquote"],
            [
                { list: "ordered" },
                { list: "bullet" },
                { indent: "-1" },
                { indent: "+1" },
            ],
            [
                {
                    color: ["red", "blue", "yellow", "#666666", "black"],
                },
            ],
            ["link", "image", "video"],
            ["clean"],
        ],
        clipboard: {
            // toggle to add extra line breaks when pasting HTML:
            matchVisual: false,
        },
    };
    /*
     * Quill editor formats
     * See https://quilljs.com/docs/formats/
     */
    const formats = [
        "header",
        "font",
        "size",
        "bold",
        "italic",
        "underline",
        "strike",
        "blockquote",
        "list",
        "bullet",
        "indent",
        "link",
        "image",
        "video",
        "color",
    ];

    const [detail, setDetail] = useState();
    const topicRef = useRef();
    

    const onChangeDetail = (value) =>{
      setDetail(currentDetail => {
        return value
      })
    }

    const test = async () => {
        const data = {
            topic: topicRef.current.value,
            detail: detail,
        };

        const res = await CreateBlog(data);
        console.log(res.data);
    };
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <label htmlFor="ftopic">Topic:</label>
                <input ref={topicRef} type="text" />
                <QuillNoSSRWrapper
                    theme="snow"
                    modules={modules}
                    formats={formats}
                    onChange={onChangeDetail}
                />
                <button onClick={test}>Test</button>

                <h2 className="text-4xl"> Pre render</h2>
                <div className="unreset" dangerouslySetInnerHTML={{__html: detail}}/>
            </main>
        </div>
    );
}
